### ISSUE TITLE
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1 Error: 🚨 Action failed

### ISSUE THREAD

**Issue by onlinedear** [movie-web/simple-proxy#21]
![20240101102156](https://github.com/movie-web/simple-proxy/assets/10751712/f4518935-6c91-4c6f-9209-47f8501ed466)

**Comment by binaryoverload** [comment]
We don't provide support for GitHub actions - please check the logs and do some research as to why it's not workint
